spring:
  datasource:
    url: jdbc:postgresql://dpg-d7ds37nlk1mc73evi9sg-a.virginia-postgres.render.com:5432/algoverse
    username: algoverse_user
    password: t5dPpWYywNr7mkVYY620Vtwldwk5llsR

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: ${PORT:8080}

logging:
  level:
    org:
      hibernate:
        SQL: debug